# -*- coding: utf-8 -*-
"""parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Ro2F2nb4AnKOH48ns5VdQYDtr82Y5PB
"""

"""
Tools for reading TextGrid files, the format used by Praat.
Module contents
===============
The textgrid corpus reader provides 4 data items and 1 function
for each textgrid file.  For each tier in the file, the reader
provides 10 data items and 2 functions.
 
For the full textgrid file: 
  - size
    The number of tiers in the file.
  - xmin
    First marked time of the file.
  - xmax
    Last marked time of the file.
  - t_time
    xmax - xmin.
  - text_type
    The style of TextGrid format:
        - ooTextFile:  Organized by tier.
        - ChronTextFile:  Organized by time.
        - OldooTextFile:  Similar to ooTextFile.
  - to_chron()
    Convert given file to a ChronTextFile format.
  - to_oo()
    Convert given file to an ooTextFile format.
For each tier:
  - text_type
    The style of TextGrid format, as above.
  - classid
    The style of transcription on this tier:
        - IntervalTier:  Transcription is marked as intervals.
        - TextTier:  Transcription is marked as single points.
  - nameid
    The name of the tier.
  - xmin
    First marked time of the tier.
  - xmax
    Last marked time of the tier.
  - size
    Number of entries in the tier.
  - transcript
    The raw transcript for the tier.
  - simple_transcript
    The transcript formatted as a list of tuples: (time1, time2, utterance).
  - tier_info
    List of (classid, nameid, xmin, xmax, size, transcript).
  - min_max()
    A tuple of (xmin, xmax).  
  - time(non_speech_marker)
    Returns the utterance time of a given tier.
    Excludes entries that begin with a non-speech marker.
"""

# needs more cleanup, subclassing, epydoc docstrings

import sys
import re

TEXTTIER = "TextTier"
INTERVALTIER = "IntervalTier"

OOTEXTFILE = re.compile(r"""(?x)
            xmin\ =\ (.*)[\r\n]+
            xmax\ =\ (.*)[\r\n]+
            [\s\S]+?size\ =\ (.*)[\r\n]+ 
""")

CHRONTEXTFILE = re.compile(r"""(?x)
            [\r\n]+(\S+)\ 
            (\S+)\ +!\ Time\ domain.\ *[\r\n]+
            (\S+)\ +!\ Number\ of\ tiers.\ *[\r\n]+"
""")

OLDOOTEXTFILE = re.compile(r"""(?x)
            [\r\n]+(\S+)
            [\r\n]+(\S+)
            [\r\n]+.+[\r\n]+(\S+)
""")



#################################################################
# TextGrid Class
#################################################################

class TextGrid(object):
    """
    Class to manipulate the TextGrid format used by Praat.
    Separates each tier within this file into its own Tier
    object.  Each TextGrid object has
    a number of tiers (size), xmin, xmax, a text type to help
    with the different styles of TextGrid format, and tiers with their
    own attributes.
    """

    def __init__(self, read_file):
        """
        Takes open read file as input, initializes attributes 
        of the TextGrid file.
        @type read_file: An open TextGrid file, mode "r".
        @param size:  Number of tiers.
        @param xmin: xmin.
        @param xmax: xmax.
        @param t_time:  Total time of TextGrid file.
        @param text_type:  TextGrid format.
        @type tiers:  A list of tier objects.
        """

        self.read_file = read_file
        self.size = 0
        self.xmin = 0
        self.xmax = 0
        self.t_time = 0
        self.text_type = self._check_type()
        self.tiers = self._find_tiers()

    def __iter__(self):
        for tier in self.tiers:
            yield tier

    def next(self):
        if self.idx == (self.size - 1):
            raise StopIteration
        self.idx += 1
        return self.tiers[self.idx]

    @staticmethod
    def load(file):
        """
        @param file: a file in TextGrid format
        """

        return TextGrid(open(file).read())

    def _load_tiers(self, header):
        """
        Iterates over each tier and grabs tier information.
        """ 

        tiers = []
        if self.text_type == "ChronTextFile":
            m = re.compile(header)
            tier_headers = m.findall(self.read_file)
            tier_re = " \d+.?\d* \d+.?\d*[\r\n]+\"[^\"]*\""
            for i in range(0, self.size):
                tier_info = [tier_headers[i]] + \
                re.findall(str(i + 1) + tier_re, self.read_file)
                tier_info = "\n".join(tier_info)
                tiers.append(Tier(tier_info, self.text_type, self.t_time))
            return tiers

        tier_re = header + "[\s\S]+?(?=" + header + "|$$)"
        m = re.compile(tier_re)
        tier_iter = m.finditer(self.read_file)
        for iterator in tier_iter:
            (begin, end) = iterator.span()
            tier_info = self.read_file[begin:end]
            tiers.append(Tier(tier_info, self.text_type, self.t_time))
        return tiers
    
    def _check_type(self):
        """
        Figures out the TextGrid format.
        """

        m = re.match("(.*)[\r\n](.*)[\r\n](.*)[\r\n](.*)", self.read_file)
        try:
            type_id = m.group(1).strip()
        except AttributeError:
            raise TypeError("Cannot read file -- try TextGrid.load()")
        xmin = m.group(4)
        if type_id == "File type = \"ooTextFile\"":
            if "xmin" not in xmin:
                text_type = "OldooTextFile"
            else:
                text_type = "ooTextFile"
        elif type_id == "\"Praat chronological TextGrid text file\"":
            text_type = "ChronTextFile"
        else: 
            raise TypeError("Unknown format '(%s)'", (type_id))
        return text_type
        
    def _find_tiers(self):
        """
        Splits the textgrid file into substrings corresponding to tiers. 
        """

        if self.text_type == "ooTextFile":
            m = OOTEXTFILE
            header = " +item \["
        elif self.text_type == "ChronTextFile":
            m = CHRONTEXTFILE
            header = "\"\S+\" \".*\" \d+\.?\d* \d+\.?\d*"
        elif self.text_type == "OldooTextFile":
            m = OLDOOTEXTFILE
            header = "\".*\"[\r\n]+\".*\""

        file_info = m.findall(self.read_file)[0]
        self.xmin = float(file_info[0])
        self.xmax = float(file_info[1])
        self.t_time = self.xmax - self.xmin
        self.size = int(file_info[2])
        tiers = self._load_tiers(header)
        return tiers

   


#################################################################
# Tier Class
#################################################################

class Tier(object):
    """ 
    A container for each tier.
    """

    def __init__(self, tier, text_type, t_time):
        """
        Initializes attributes of the tier: class, name, xmin, xmax
        size, transcript, total time.  
        Utilizes text_type to guide how to parse the file.
        @type tier: a tier object; single item in the TextGrid list.
        @param text_type:  TextGrid format
        @param t_time:  Total time of TextGrid file.
        @param classid:  Type of tier (point or interval).
        @param nameid:  Name of tier.
        @param xmin:  xmin of the tier.
        @param xmax:  xmax of the tier.
        @param size:  Number of entries in the tier
        @param transcript:  The raw transcript for the tier.
        """

        self.tier = tier
        self.text_type = text_type
        self.t_time = t_time
        self.classid = ""
        self.nameid = ""
        self.xmin = 0
        self.xmax = 0
        self.size = 0
        self.transcript = ""
        self.tier_info = ""
        self._make_info()
        self.simple_transcript = self.make_simple_transcript()
        if self.classid != TEXTTIER:
            self.mark_type = "intervals"
        else:
            self.mark_type = "points"
            self.header = [("class", self.classid), ("name", self.nameid), \
            ("xmin", self.xmin), ("xmax", self.xmax), ("size", self.size)]

    def __iter__(self):
        return self
  
    def _make_info(self):
        """
        Figures out most attributes of the tier object:
        class, name, xmin, xmax, transcript.
        """

        trans = "([\S\s]*)"
        if self.text_type == "ChronTextFile":
            classid = "\"(.*)\" +"
            nameid = "\"(.*)\" +"
            xmin = "(\d+\.?\d*) +"
            xmax = "(\d+\.?\d*) *[\r\n]+"
            # No size values are given in the Chronological Text File format.
            self.size = None
            size = ""
        elif self.text_type == "ooTextFile":
            classid = " +class = \"(.*)\" *[\r\n]+"
            nameid = " +name = \"(.*)\" *[\r\n]+"
            xmin = " +xmin = (\d+\.?\d*) *[\r\n]+"
            xmax = " +xmax = (\d+\.?\d*) *[\r\n]+"
            size = " +\S+: size = (\d+) *[\r\n]+"
        elif self.text_type == "OldooTextFile":
            classid = "\"(.*)\" *[\r\n]+"
            nameid = "\"(.*)\" *[\r\n]+"
            xmin = "(\d+\.?\d*) *[\r\n]+"
            xmax = "(\d+\.?\d*) *[\r\n]+"
            size = "(\d+) *[\r\n]+"
        m = re.compile(classid + nameid + xmin + xmax + size + trans)
        self.tier_info = m.findall(self.tier)[0]
        self.classid = self.tier_info[0]
        self.nameid = self.tier_info[1]
        self.xmin = float(self.tier_info[2])
        self.xmax = float(self.tier_info[3])
        if self.size != None:
            self.size = int(self.tier_info[4])
        self.transcript = self.tier_info[-1]
            
    def make_simple_transcript(self):
        """ 
        @return:  Transcript of the tier, in form [(start_time end_time label)]
        """

        if self.text_type == "ChronTextFile":
            trans_head = ""
            trans_xmin = " (\S+)"
            trans_xmax = " (\S+)[\r\n]+"
            trans_text = "\"([\S\s]*?)\""
        elif self.text_type == "ooTextFile":
            trans_head = " +\S+ \[\d+\]: *[\r\n]+"
            trans_xmin = " +\S+ = (\S+) *[\r\n]+"
            trans_xmax = " +\S+ = (\S+) *[\r\n]+"
            trans_text = " +\S+ = \"([^\"]*?)\""    
        elif self.text_type == "OldooTextFile":
            trans_head = ""
            trans_xmin = "(.*)[\r\n]+"
            trans_xmax = "(.*)[\r\n]+"
            trans_text = "\"([\S\s]*?)\""
        if self.classid == TEXTTIER:
            trans_xmin = ""
        trans_m = re.compile(trans_head + trans_xmin + trans_xmax + trans_text)
        self.simple_transcript = trans_m.findall(self.transcript)
        return self.simple_transcript

    def transcript(self):
        """
        @return:  Transcript of the tier, as it appears in the file.
        """
       
        return self.transcript

    def time(self, non_speech_char="."):
        """
        @return: Utterance time of a given tier.
        Screens out entries that begin with a non-speech marker.        
        """

        total = 0.0
        if self.classid != TEXTTIER:
            for (time1, time2, utt) in self.simple_transcript:
                utt = utt.strip()
                if utt and not utt[0] == ".":
                    total += (float(time2) - float(time1))
        return total
                    
    def tier_name(self):
        """
        @return:  Tier name of a given tier.
        """

        return self.nameid

    def classid(self):
        """
        @return:  Type of transcription on tier.
        """

        return self.classid

    def min_max(self):
        """
        @return:  (xmin, xmax) tuple for a given tier.
        """

        return (self.xmin, self.xmax)

    def __repr__(self):
        return "<%s \"%s\" (%.2f, %.2f) %.2f%% %.2f-sec>" % (self.classid, 
                                                          self.nameid,
                                                          self.xmin,
                                                          self.xmax,
                                                          100*self.time()/self.t_time,
                                                          self.time())

    def __str__(self):
        return self.__repr__() + "\n  " + "\n  ".join(" ".join(row) for row in self.simple_transcript)

"""##Run

##Example
"""

demo_data1 = """File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0 
xmax = 300.0250566893424 
tiers? <exists> 
size = 11 
item []: 
    item [1]:
        class = "IntervalTier" 
        name = "1/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 7 
        intervals [1]:
            xmin = 0 
            xmax = 16.917822662601626 
            text = "" 
        intervals [2]:
            xmin = 16.917822662601626 
            xmax = 25.105119410569106 
            text = "笑い転げて、やがて悲しい。" 
        intervals [3]:
            xmin = 25.105119410569106 
            xmax = 25.345922256097563 
            text = "" 
        intervals [4]:
            xmin = 25.345922256097563 
            xmax = 36.648590283807565 
            text = "この町は、泣き笑いサーカス。" 
        intervals [5]:
            xmin = 36.648590283807565 
            xmax = 37.85331600849138 
            text = "" 
        intervals [6]:
            xmin = 37.85331600849138 
            xmax = 49.08504873206863 
            text = "この町は、泣き笑いサーカス。" 
        intervals [7]:
            xmin = 49.08504873206863 
            xmax = 300.0250566893424 
            text = "" 
    item [2]:
        class = "IntervalTier" 
        name = "2/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 48 
        intervals [1]:
            xmin = 0 
            xmax = 56.6989970866847 
            text = "" 
        intervals [2]:
            xmin = 56.6989970866847 
            xmax = 58.45341781839202 
            text = "よ！" 
        intervals [3]:
            xmin = 58.45341781839202 
            xmax = 63.493077371237554 
            text = "" 
        intervals [4]:
            xmin = 63.493077371237554 
            xmax = 64.38748794034325 
            text = "お帰り。" 
        intervals [5]:
            xmin = 64.38748794034325 
            xmax = 68.03535387384468 
            text = "" 
        intervals [6]:
            xmin = 68.03535387384468 
            xmax = 71.64739655677151 
            text = "岡山の五十川さん、お元気だったんすか？" 
        intervals [7]:
            xmin = 71.64739655677151 
            xmax = 75.9646475730317 
            text = "" 
        intervals [8]:
            xmin = 75.9646475730317 
            xmax = 80.33349919904796 
            text = "金田一さんの水準また、解答欄を作った人だったんでしょ。" 
        intervals [9]:
            xmin = 80.33349919904796 
            xmax = 135.54580412907805 
            text = "" 
        intervals [10]:
            xmin = 135.54580412907805 
            xmax = 137.76463034859023 
            text = "一体、どういうことですよね。" 
        intervals [11]:
            xmin = 137.76463034859023 
            xmax = 138.14303482013494 
            text = "" 
        intervals [12]:
            xmin = 138.14303482013494 
            xmax = 144.81671368192357 
            text = "我々、命を狙われたとしか思えませんが、単なるマグネシウムのたけすぎでしょう？" 
        intervals [13]:
            xmin = 144.81671368192357 
            xmax = 153.8683144295929 
            text = "" 
        intervals [14]:
            xmin = 153.8683144295929 
            xmax = 157.44595670601566 
            text = "また恐ろしい偶然が重なりそうだなんつんじゃないでしょうね。" 
        intervals [15]:
            xmin = 157.44595670601566 
            xmax = 159.11437642146282 
            text = "" 
        intervals [16]:
            xmin = 159.11437642146282 
            xmax = 160.52479308812948 
            text = "あんた、頼むよ。" 
        intervals [17]:
            xmin = 160.52479308812948 
            xmax = 160.9031975596742 
            text = "" 
        intervals [18]:
            xmin = 160.9031975596742 
            xmax = 162.70921890113763 
            text = "勘弁してよ。" 
        intervals [19]:
            xmin = 162.70921890113763 
            xmax = 163.65952376708714 
            text = "" 
        intervals [20]:
            xmin = 163.65952376708714 
            xmax = 171.2104129947294 
            text = "血が汚れてるとか、出生の秘密とか、いつもそんなおどろおどろしいことばっかりありゃしませんよ。" 
        intervals [21]:
            xmin = 171.2104129947294 
            xmax = 174.6826945556518 
            text = "" 
        intervals [22]:
            xmin = 174.6826945556518 
            xmax = 179.34394963695263 
            text = "それより金田一さん、私はここんとこめっぽう忙しいですよ。" 
        intervals [23]:
            xmin = 179.34394963695263 
            xmax = 181.26463056513342 
            text = "" 
        intervals [24]:
            xmin = 181.26463056513342 
            xmax = 184.1198643049708 
            text = "泥棒騒ぎで。" 
        intervals [25]:
            xmin = 184.1198643049708 
            xmax = 185.66788259765372 
            text = "" 
        intervals [26]:
            xmin = 185.66788259765372 
            xmax = 186.9750980448082 
            text = "泥棒。" 
        intervals [27]:
            xmin = 186.9750980448082 
            xmax = 271.1607192277123 
            text = "" 
        intervals [28]:
            xmin = 271.1607192277123 
            xmax = 273.3107446342164 
            text = "とにかくよ。" 
        intervals [29]:
            xmin = 273.3107446342164 
            xmax = 273.6719489025091 
            text = "" 
        intervals [30]:
            xmin = 273.6719489025091 
            xmax = 275.8219743090131 
            text = "デカが角刈りにサングラス。" 
        intervals [31]:
            xmin = 275.8219743090131 
            xmax = 275.94237573177736 
            text = "" 
        intervals [32]:
            xmin = 275.94237573177736 
            xmax = 278.26440317080176 
            text = "おまけにたいよみはほえたがる。" 
        intervals [33]:
            xmin = 278.26440317080176 
            xmax = 278.38909843066625 
            text = "" 
        intervals [34]:
            xmin = 278.38909843066625 
            xmax = 281.6227366420484 
            text = "まったくテレビの見過ぎだってんだ。" 
        intervals [35]:
            xmin = 281.6227366420484 
            xmax = 281.7947386745687 
            text = "" 
        intervals [36]:
            xmin = 281.7947386745687 
            xmax = 283.6867610322923 
            text = "ギャラ上げろ。" 
        intervals [37]:
            xmin = 283.6867610322923 
            xmax = 286.696796601398 
            text = "ギャラじゃないのデカはがっちよ。" 
        intervals [38]:
            xmin = 286.696796601398 
            xmax = 286.81719802416217 
            text = "" 
        intervals [39]:
            xmin = 286.81719802416217 
            xmax = 289.2768270892028 
            text = "おめえら、取り壊しが始まってんだ。" 
        intervals [40]:
            xmin = 289.2768270892028 
            xmax = 289.4197086698482 
            text = "" 
        intervals [41]:
            xmin = 289.4197086698482 
            xmax = 292.0857401614416 
            text = "引っ越しの準備ぐらいしたらどうなんだ？" 
        intervals [42]:
            xmin = 292.0857401614416 
            xmax = 293.2037533675937 
            text = "" 
        intervals [43]:
            xmin = 293.2037533675937 
            xmax = 294.4249677927752 
            text = "電話だろ。" 
        intervals [44]:
            xmin = 294.4249677927752 
            xmax = 294.5281690118046 
            text = "" 
        intervals [45]:
            xmin = 294.5281690118046 
            xmax = 295.5601812020988 
            text = "電話だよ！" 
        intervals [46]:
            xmin = 295.5601812020988 
            xmax = 297.4006029414569 
            text = "" 
        intervals [47]:
            xmin = 297.4006029414569 
            xmax = 300.0150338235356 
            text = "やたら、吠えるな。" 
        intervals [48]:
            xmin = 300.0150338235356 
            xmax = 300.0250566893424 
            text = "" 
    item [3]:
        class = "IntervalTier" 
        name = "3/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 23 
        intervals [1]:
            xmin = 0 
            xmax = 60.414240989123726 
            text = "" 
        intervals [2]:
            xmin = 60.414240989123726 
            xmax = 61.51505399725381 
            text = "どうも、どうも。" 
        intervals [3]:
            xmin = 61.51505399725381 
            xmax = 61.60105501351397 
            text = "" 
        intervals [4]:
            xmin = 61.60105501351397 
            xmax = 63.235074322457066 
            text = "どうも、お待たせ。" 
        intervals [5]:
            xmin = 63.235074322457066 
            xmax = 64.74869220863593 
            text = "" 
        intervals [6]:
            xmin = 64.74869220863593 
            xmax = 66.62351436310747 
            text = "待った？" 
        intervals [7]:
            xmin = 66.62351436310747 
            xmax = 71.87099919904794 
            text = "" 
        intervals [8]:
            xmin = 71.87099919904794 
            xmax = 74.00382440229998 
            text = "元気、元気！" 
        intervals [9]:
            xmin = 74.00382440229998 
            xmax = 80.68179710118886 
            text = "" 
        intervals [10]:
            xmin = 80.68179710118886 
            xmax = 82.21261519061976 
            text = "そうじゃ、そうじゃ！" 
        intervals [11]:
            xmin = 82.21261519061976 
            xmax = 82.79742210118887 
            text = "" 
        intervals [12]:
            xmin = 82.79742210118887 
            xmax = 83.4510298247661 
            text = "さあ、さあ。" 
        intervals [13]:
            xmin = 83.4510298247661 
            xmax = 83.46823002801814 
            text = "" 
        intervals [14]:
            xmin = 83.46823002801814 
            xmax = 84.55184283289618 
            text = "行きましょうか？" 
        intervals [15]:
            xmin = 84.55184283289618 
            xmax = 145.00591591769592 
            text = "" 
        intervals [16]:
            xmin = 145.00591591769592 
            xmax = 147.22474213720812 
            text = "ああ、そうかな？" 
        intervals [17]:
            xmin = 147.22474213720812 
            xmax = 147.4827451859886 
            text = "" 
        intervals [18]:
            xmin = 147.4827451859886 
            xmax = 153.52431036455226 
            text = "しかしね私の推理のよると、あの女としゃしんや、どうも初めからくさなった。" 
        intervals [19]:
            xmin = 153.52431036455226 
            xmax = 156.96435101495877 
            text = "" 
        intervals [20]:
            xmin = 156.96435101495877 
            xmax = 159.11437642146282 
            text = "ええ、それそれ、それですよ。" 
        intervals [21]:
            xmin = 159.11437642146282 
            xmax = 171.58665797028596 
            text = "" 
        intervals [22]:
            xmin = 171.58665797028596 
            xmax = 173.65068236052986 
            text = "そうかなあ。" 
        intervals [23]:
            xmin = 173.65068236052986 
            xmax = 300.0250566893424 
            text = "" 
    item [4]:
        class = "IntervalTier" 
        name = "4/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 11 
        intervals [1]:
            xmin = 0 
            xmax = 85.11944954021327 
            text = "" 
        intervals [2]:
            xmin = 85.11944954021327 
            xmax = 87.13187332070108 
            text = "カノウさん。" 
        intervals [3]:
            xmin = 87.13187332070108 
            xmax = 87.49307758899376 
            text = "" 
        intervals [4]:
            xmin = 87.49307758899376 
            xmax = 91.48352474346531 
            text = "本当にいいんですかね、探偵がこんなまねしてて。" 
        intervals [5]:
            xmin = 91.48352474346531 
            xmax = 95.66817946785098 
            text = "" 
        intervals [6]:
            xmin = 95.66817946785098 
            xmax = 100.79384003695668 
            text = "いや、もう好きなんだから、映画でも本でもこれであたるんなら結構なことこっちゃない？" 
        intervals [7]:
            xmin = 100.79384003695668 
            xmax = 101.44815925757546 
            text = "" 
        intervals [8]:
            xmin = 101.44815925757546 
            xmax = 102.15336759090879 
            text = "まあ。" 
        intervals [9]:
            xmin = 102.15336759090879 
            xmax = 103.34018161529903 
            text = "" 
        intervals [10]:
            xmin = 103.34018161529903 
            xmax = 107.8638350705836 
            text = "それより、付き合わされる私の身にもなってくださいよ。" 
        intervals [11]:
            xmin = 107.8638350705836 
            xmax = 300.0250566893424 
            text = "" 
    item [5]:
        class = "IntervalTier" 
        name = "5/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 9 
        intervals [1]:
            xmin = 0 
            xmax = 92.45174145972089 
            text = "" 
        intervals [2]:
            xmin = 92.45174145972089 
            xmax = 94.13736137842008 
            text = "いいんじゃないですか。" 
        intervals [3]:
            xmin = 94.13736137842008 
            xmax = 94.42976483370464 
            text = "" 
        intervals [4]:
            xmin = 94.42976483370464 
            xmax = 95.56497824833879 
            text = "おすきなのに。" 
        intervals [5]:
            xmin = 95.56497824833879 
            xmax = 99.8478288580949 
            text = "" 
        intervals [6]:
            xmin = 99.8478288580949 
            xmax = 101.41304735402986 
            text = "そうなります。" 
        intervals [7]:
            xmin = 101.41304735402986 
            xmax = 109.66698556902982 
            text = "" 
        intervals [8]:
            xmin = 109.66698556902982 
            xmax = 113.81223455276967 
            text = "いやあ、あなたのかいんどうえおんなかなかきまってますよ。" 
        intervals [9]:
            xmin = 113.81223455276967 
            xmax = 300.0250566893424 
            text = "" 
    item [6]:
        class = "IntervalTier" 
        name = "6/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 1 
        intervals [1]:
            xmin = 0 
            xmax = 300.0250566893424 
            text = "" 
    item [7]:
        class = "IntervalTier" 
        name = "7/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 1 
        intervals [1]:
            xmin = 0 
            xmax = 300.0250566893424 
            text = "" 
    item [8]:
        class = "IntervalTier" 
        name = "8/M" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 1 
        intervals [1]:
            xmin = 0 
            xmax = 300.0250566893424 
            text = "" 
    item [9]:
        class = "IntervalTier" 
        name = "1/F" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 7 
        intervals [1]:
            xmin = 0 
            xmax = 116.5298666665908 
            text = "" 
        intervals [2]:
            xmin = 116.5298666665908 
            xmax = 120.03870813000545 
            text = "ではしごうをつづ審で、本番行くわよ。" 
        intervals [3]:
            xmin = 120.03870813000545 
            xmax = 123.8578647489982 
            text = "" 
        intervals [4]:
            xmin = 123.8578647489982 
            xmax = 126.00789015550227 
            text = "楽な気分になって。" 
        intervals [5]:
            xmin = 126.00789015550227 
            xmax = 126.0766909685104 
            text = "" 
        intervals [6]:
            xmin = 126.0766909685104 
            xmax = 130.47994300103073 
            text = "そう、ワン、ツー、アクション！" 
        intervals [7]:
            xmin = 130.47994300103073 
            xmax = 300.0250566893424 
            text = "" 
    item [10]:
        class = "IntervalTier" 
        name = "2/F" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 5 
        intervals [1]:
            xmin = 0 
            xmax = 227.0278933808651 
            text = "" 
        intervals [2]:
            xmin = 227.0278933808651 
            xmax = 229.77992590119027 
            text = "上手く、上手くいった！" 
        intervals [3]:
            xmin = 229.77992590119027 
            xmax = 231.5350581299391 
            text = "" 
        intervals [4]:
            xmin = 231.5350581299391 
            xmax = 234.01188739823178 
            text = "上手くいった！" 
        intervals [5]:
            xmin = 234.01188739823178 
            xmax = 300.0250566893424 
            text = "" 
    item [11]:
        class = "IntervalTier" 
        name = "3/F" 
        xmin = 0 
        xmax = 300.0250566893424 
        intervals: size = 1 
        intervals [1]:
            xmin = 0 
            xmax = 300.0250566893424 
            text = "" 
 """

"""# RUN"""

import re
import pandas as pd

total__utteranceTime = []
total_maxTime = ""
total_minTime = ""


def demo_TextGrid(file, output="output.csv"):
    print("** Demo of the TextGrid class. **")

    fid = TextGrid.load(file)
    print("Tiers: %s" % (fid.size))

    for i, tier in enumerate(fid):
        print("\n***")
        print("Tier: %s" % (i + 1))

        total__utteranceTime.append(float(re.search(r'(\d+.\d+)-sec',str(tier)).group().replace("-sec","")))
        total_maxTime=re.search(r'\(\d.*\)',str(tier)).group().split(',')[1].replace(')','')
        total_minTime=re.search(r'\(\d.*\)',str(tier)).group().split(',')[0].replace('(','')
       
        print(tier)
    
    results_Dict = {'Filenames':file, 'Utterence of file':sum(total__utteranceTime), 'Total Time':total_maxTime}
    df = pd.DataFrame(results_Dict, index=[0])
    df.to_csv(output, mode='a')
    print(df)
    print(f"\n\n")
    print(f"***\nTotal Utterence of file is: {sum(total__utteranceTime)} sec from {total_maxTime}. \n***")



import sys, getopt

def main(argv):
   inputfile = ''
   outputfile = ''
   try:
      opts, args = getopt.getopt(argv,"hi:o:",["ifile=","ofile="])
   except getopt.GetoptError:
      print('test.py -i <inputfile> -o <outputfile>')
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-h':
         print('test.py -i <inputfile> -o <outputfile>')
         sys.exit()
      elif opt in ("-i", "--ifile"):
         inputfile = arg
      elif opt in ("-o", "--ofile"):
         outputfile = arg
   print(f'Input file is: {inputfile}')
   demo_TextGrid(inputfile, outputfile)


if __name__ == "__main__":
   main(sys.argv[1:])